### ISSUE TITLE
:\

### ISSUE THREAD

**Issue by zeroninefourfour** [NXTS-Developers/PROJECT-HUSTAL#1]
template/css/bootstrap.min.css  not exists.
cPanel Login/File Manger Button Not Worked

includes/header.php
```php
<?php
include __DIR__."/connect.php";
?>
```
-->
```php
<?php
include __DIR__."/config.php";
?>
```

**Comment by mahtab2003** [comment]
Hello
Uper error had been fixed.
Did you added api username and password and white list your server ip address in MOFH Reseller panel?

**Comment by zeroninefourfour** [comment]
Y

**Comment by mahtab2003** [comment]
This is rule for HUSTAL to work
