### ISSUE TITLE
random subdomain name 

### ISSUE THREAD

**Issue by zeroninefourfour** [NXTS-Developers/PROJECT-HUSTAL#10]
i just update to SSL Version Hustal.I found another bug...
Random Subdomain Name
Example:
Sub Domain Name Is NodeJS.domain.tld
but Client Area And vP Show Random  Sub Domain Name
vP:
![圖片](https://user-images.githubusercontent.com/69704016/133868998-5e1062e0-ace6-4134-b251-8950a00e8504.png)
Client Area:
![圖片](https://user-images.githubusercontent.com/69704016/133869030-a02c24f9-80c1-4fc9-9a55-3905bbb05ea3.png)

**Comment by mahtab2003** [comment]
This is main domain generated by iFastNet I can't do anything.😌

**Comment by zeroninefourfour** [comment]
ok.

**Comment by zeroninefourfour** [comment]
i just found some thing.
cpanel username is sub domains?
![圖片](https://user-images.githubusercontent.com/69704016/133879398-56d90ca0-c16d-4605-87ae-3aa357387648.png)
![圖片](https://user-images.githubusercontent.com/69704016/133879408-d7713a78-b05b-4762-8e2d-9a5cccf3904d.png)

**Comment by zeroninefourfour** [comment]
@mahtab2003

**Comment by mahtab2003** [comment]
Yes I know that
