### ISSUE TITLE
Tickets Security issue

### ISSUE THREAD

**Issue by zeroninefourfour** [NXTS-Developers/PROJECT-HUSTAL#16]
You Can Use HTML in Tickets.It means it can inject JavaScript.(i guess)

**Comment by zeroninefourfour** [comment]
![圖片](https://user-images.githubusercontent.com/69704016/134791882-38d5841e-bbee-421c-afb4-d01922f7b5bb.png)

**Comment by mahtab2003** [comment]
Ok wait I will fix it

**Comment by mahtab2003** [comment]
Fixed now html content cannot be executed in ticket content
