### ISSUE TITLE
Letsencrpty ssl

### ISSUE THREAD

**Issue by gautamjethe** [NXTS-Developers/PROJECT-HUSTAL#21]
hello can you add letsencrypt ssl instead of gogetssl

**Comment by mahtab2003** [comment]
I don't know how let's encrypt work

**Comment by gautamjethe** [comment]
ok can we get gogetssl reseller account for free

**Comment by mahtab2003** [comment]
Yesl

**Comment by gautamjethe** [comment]
how to get it can you guide me

**Comment by mahtab2003** [comment]
Sure create an account on my.gogetssl.com then go to menu > reseller modules > api settings and click on become a reseller and fill up form after 2 hours you will be able to resell free ssl

**Comment by gautamjethe** [comment]
is this one you are saying https://www.gogetssl.com/reseller-program/

**Comment by gautamjethe** [comment]
i solved my ssl problem. how to change navbar colour to black

**Comment by mahtab2003** [comment]
> is this one you are saying https://www.gogetssl.com/reseller-program/

Yes

**Comment by mahtab2003** [comment]
> i solved my ssl problem. how to change navbar colour to black

Edit navbar.php
