### ISSUE TITLE
Signup form not working

### ISSUE THREAD

**Issue by Gouravyadavyt** [NXTS-Developers/PROJECT-HUSTAL#27]
I recently installed this script and when I try signup .php it show error  please try to help me
Link :https://easyteachhost.tk/clientarea/signup.php

**Comment by ritikraj0315** [comment]
have you setup your database and config.php ?

**Comment by ritikraj0315** [comment]
> I recently installed this script and when I try signup .php it show error please try to help me Link :https://easyteachhost.tk/clientarea/signup.php

?

**Comment by Gouravyadavyt** [comment]
Yes all done

**Comment by Gouravyadavyt** [comment]
Config.php done 
Database table and cofig done
Login system is working mean config php and database work properly.

**Comment by pheonixfreehost** [comment]
> Config.php done Database table and cofig done Login system is working mean config php and database work properly.

Ok I will send you the stable script 🙂.

**Comment by pheonixfreehost** [comment]
> I recently installed this script and when I try signup .php it show error please try to help me Link :https://easyteachhost.tk/clientarea/signup.php

Mine also not working but i fixed it 🙂

**Comment by Gouravyadavyt** [comment]
Ok thanks
Mail id: codingwithgourav@gmail.com

**Comment by Gouravyadavyt** [comment]
Thanks for understand my website low power situation

**Comment by ritikraj0315** [comment]
> Thanks for understand my website low power situation
Download it from here 
https://github.com/ritikraj0315/Project-Hustal-Stable

**Comment by Gouravyadavyt** [comment]
> > Thanks for understand my website low power situation
> > Download it from here
> > https://github.com/ritikraj0315/Project-Hustal-Stable

Sorry brother but it same

**Comment by ritikraj0315** [comment]
> > > Thanks for understand my website low power situation
> > > Download it from here
> > > https://github.com/ritikraj0315/Project-Hustal-Stable
> 
> Sorry brother but it same

Bro its stable and signup page is working fine.

**Comment by ritikraj0315** [comment]
> > > Thanks for understand my website low power situation
> > > Download it from here
> > > https://github.com/ritikraj0315/Project-Hustal-Stable
> 
> Sorry brother but it same

try first
