### ISSUE TITLE
Page shows "SITE_NAME" placeholder, yet it is not blank in the config.php

### ISSUE THREAD

**Issue by Naidru** [NXTS-Developers/PROJECT-HUSTAL#3]
Hey there! At https://host.networkbay.org/ the "SITE_NAME" does not show up at NetworkHost like I have set it to. However on the admin page, it does.

https://i.imgur.com/rLpYQ2j.png

Also you might want to take a look at the countdown timer since it displays as a "-"

**Comment by zeroninefourfour** [comment]
edit includes/header.php
<?php
include __DIR__."/config.php";
?>

**Comment by zeroninefourfour** [comment]
```
<?php
include __DIR__."/connect.php";
?>
```
-->
```
<?php
include __DIR__."/config.php";
?>
```

**Comment by mahtab2003** [comment]
Error had been fixed thank you

**Comment by mahtab2003** [comment]
> Hey there! At https://host.networkbay.org/ the "SITE_NAME" does not show up at NetworkHost like I have set it to. However on the admin page, it does.
> 
> https://i.imgur.com/rLpYQ2j.png
> 
> Also you might want to take a look at the countdown timer since it displays as a "-"

If you want to change countdown timer you need to change date in /clientarea/home.php line 54
