### ISSUE TITLE
client area wont show correct domains

### ISSUE THREAD

**Issue by zeroninefourfour** [NXTS-Developers/PROJECT-HUSTAL#9]
please fix.client area wont show correct domains.
![圖片](https://user-images.githubusercontent.com/69704016/132988923-b782539e-5305-458f-825f-afd093505d11.png)
mofh:
![圖片](https://user-images.githubusercontent.com/69704016/132988928-eca53001-3e71-4a8c-bb8d-91c117c08f71.png)
vP Show Wrong Domains too!
![圖片](https://user-images.githubusercontent.com/69704016/132988953-c1be3e5d-b610-4f36-847e-f2da36fd3470.png)

**Comment by mahtab2003** [comment]
Wait you had set the SITE_ADDR constant to ```000host.eu.org/application/client``` you need to change it to ```000host.eu.org```

**Comment by mahtab2003** [comment]
![Uploading IMG_20210912_203728.png…]()

**Comment by mahtab2003** [comment]
![Uploading IMG_20210912_203728.png…]()

**Comment by zeroninefourfour** [comment]
> Wait you had set the SITE_ADDR constant to ```000host.eu.org/application/client``` you need to change it to ```000host.eu.org```

Ik....  why Label is Sub Domain Name...After I go to that address... Supsended Acc

**Comment by mahtab2003** [comment]
> > Wait you had set the SITE_ADDR constant to `000host.eu.org/application/client` you need to change it to `000host.eu.org`
> 
> Ik.... why Label is Sub Domain Name...After I go to that address... Supsended Acc

I don't know can you send screenshot

**Comment by zeroninefourfour** [comment]
> > > Wait you had set the SITE_ADDR constant to `000host.eu.org/application/client` you need to change it to `000host.eu.org`
> > 
> > Ik.... why Label is Sub Domain Name...After I go to that address... Supsended Acc
> 
> I don't know can you send screenshot 

That pic is screen shot
See mofh pic then see client area pic

**Comment by mahtab2003** [comment]
you had set the SITE_ADDR constant to ```000host.eu.org/application/client``` in ```includes/config.php``` you need to change it to ```000host.eu.org```

**Comment by zeroninefourfour** [comment]
> > Wait you had set the SITE_ADDR constant to ```000host.eu.org/application/client``` you need to change it to ```000host.eu.org```
> 
> Ik....  why Label is Sub Domain Name...After I go to that address... Supsended Acc

😕

**Comment by zeroninefourfour** [comment]
>  you had set the SITE_ADDR constant to ```000host.eu.org/application/client``` in ```includes/config.php``` you need to change it to ```000host.eu.org```

Ok.
mofh show testhost.000host.eu.org
Client Area,vp Show hdhyd765.000host.eu.org
After I go to hdhyd765.000host.eu.org, supsended account.

**Comment by mahtab2003** [comment]
You need to open a support ticket maybe there is misconfigration
I created a subdomain hustal.000host.eu.org and it works fine.

**Comment by zeroninefourfour** [comment]
i just update the hustal. it fixed now :)

**Comment by mahtab2003** [comment]
Ah OK

**Comment by Gouravyadavyt** [comment]
My resister page is note working showing 500 error link : https://easyteachhost.easyteach.ml/clientarea/signup.php

**Comment by Gouravyadavyt** [comment]
Please 🙏 help me

**Comment by mahtab2003** [comment]
> Please 🙏 help me

Turn on display error from cpanel
